### ISSUE TITLE
[Feat] 암장 API 및 기존 로직 일부 수정

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Ji-Un-Gil/ClpetitionServer#14]
## To-do 🧑‍💻
- [ ] Gym 엔티티 수정 및 관련 API 개발
- [ ] Record '관련 암장 기록' API 추가
- [ ] Record 관련 지연로딩으로 인해 이미지가 불러오지 않아 발생하는 오류 해결 (명시적 가져오기)
- [ ] 기타 일부 로직 리팩토링, 요구사항에 따른 일부 기능 수정

## ETC ➕
