### ISSUE TITLE
[Feat] 이달의리그, 다른사람 기록 조회 API 관련

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Ji-Un-Gil/ClpetitionServer#32]
## To-do 🧑‍💻
- [ ] 프로필 조회 API에 이달의리그 관련 기록 응답으로 추가 제공
- [ ] (GET /record/{recordId} API) 다른 사람 기록 조회 시에는 다른 사람의 닉네임 및 이달의리그 관련 기록 응답 추가 제공
- [ ] + 다른 사람 기록 조회가 가능하도록 기존의 Record API 수정 필요
- [ ] + 다른 사람 기록은 public 상태만 조회가 가능하도록 로직 추가
- [ ] 홈 화면 이달의리그 api

## ETC ➕
